name: setup-postgres-action
description: Set up and teardown a PostgreSQL database
inputs:
  connection-string-name:
    description: The name of the environment variable to fill with the PostgreSQL connection string.
    required: true    
  tag:
    description: When the action runs on a Windows agent, this tag is applied to the Azure container which is created by the action.
    required: true
  init-script:
    description: The path to a script to execute in PSQL when the database is available.
    required: false    
  registry-login-server:
    description: The container registry to log in to, if required
    required: false
    default: index.docker.io
  registry-username:
    description: The username to log in to the container registry. Will not attempt login if not provided.
    required: false
  registry-password:
    description: The password to log in to the container registry. Will not attempt login if not provided.
    required: false    
runs:
  using: node20
  main: dist/index.js
  post: dist/index.js
